[project]
name = "aperture"
version = "0.1.0"
description = "Aperture Command & Control"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.10.1",
    "loguru>=0.7.3",
    "aperture-protos",
]

[project.scripts]
aperture-server = "aperture.main:start"

[tool.uv.sources]
aperture-protos = { git = "https://github.com/NadavKahlon/aperture-protos.git" }

[dependency-groups]
dev = [
    "black>=26.3.1",
]

[tool.uv]
package = true
